### PR TITLE
Version 0.2

### PR DESCRIPTION
**Pull request by tonyg**
Hi Chris,

Thanks for publishing this package on pypi!

In the three-ish years since it was published, there have been some small changes: a semverish minor version increment, more or less.

Would you be willing to update your fork and update pypi?

Regards,
  Tony

### CODE REVIEW

**Comment by Shadowfiend** [comment]
:wave: different team maintaining things over here now! We'll see what we can do here. Would you prefer publish rights of some sort for this package?

**Comment by tonyg** [comment]
@Shadowfiend that sounds good! I'd appreciate that.

**Comment by tonyg** [comment]
My pypi username is `tonyg`.

**Comment by Shadowfiend** [comment]
Ok, cool. I might be overpromising, hoping I don't underdeliver, but we'll do what we can to get that squared away!

**Comment by tonyg** [comment]
Thanks. If it works out, that's great; if not, at least the package that's up there is more-or-less OK as far as I'm aware :-)

**Comment by chris-martin** [comment]
Hey @tonyg, sorry I wasn't watching this repo! I just added you as an owner on https://pypi.org/project/tonyg-rfc3339/. I think we're planning to archive this fork if that's okay with you. Personally I'm pretty far removed from Python these days.

**Comment by Shadowfiend** [comment]
Mostly apologies are due from* me; I meant to reach out sooner than today.

If you're down @tonyg, I'm going to close this PR + archive the repo.

**Pull request closed without merging**
